/* Write your T-SQL query statement below */

SELECT EMPT.DEPARTMENT, NAME AS EMPLOYEE, EMPT.SALARY FROM EMPLOYEE EMPS 
JOIN
(SELECT MAX(SALARY) AS SALARY,DEPT.NAME AS DEPARTMENT, DEPT.ID AS ID FROM EMPLOYEE EMP
JOIN DEPARTMENT DEPT ON EMP.DEPARTMENTID = DEPT.ID
GROUP BY DEPT.ID, DEPT.NAME, DEPT.ID) AS EMPT
ON EMPS.SALARY = EMPT.SALARY and EMPS.DEPARTMENTID = EMPT.ID